In [3]:
import numpy as np

ten = np.zeros((9,9))

for i in range(0,9):
    for j in range(0,9):
        ten[i][j] = np.random.random_sample()*10
        
np.mean(ten)

4.571553663486116

In [227]:
a = np.vstack([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [263]:
def box(x,y):
    top = np.array([1]*x)
    middle = np.array([1]+[0]*(x-2)+[1])
    bottom = np.array([1]*x)
    #return np.stack((top,middle,bottom))
    print(top)
    for i in range(0,y-2):
        print(middle)
    print(bottom)
    
    
box(10,20)

[1 1 1 1 1 1 1 1 1 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 1]
[1 1 1 1 1 1 1 1 1 1]


In [12]:
angle = np.array([0,15,30,45,60,75,90])
print(np.sin(angle))
print(np.cos(angle))
print(np.tan(angle))

print(np.sin(-angle))
print(np.cos(-angle))
print(np.tan(-angle))

[ 0.          0.65028784 -0.98803162  0.85090352 -0.30481062 -0.38778164
  0.89399666]
[ 1.         -0.75968791  0.15425145  0.52532199 -0.95241298  0.92175127
 -0.44807362]
[ 0.         -0.8559934  -6.4053312   1.61977519  0.32004039 -0.42070095
 -1.99520041]
[ 0.         -0.65028784  0.98803162 -0.85090352  0.30481062  0.38778164
 -0.89399666]
[ 1.         -0.75968791  0.15425145  0.52532199 -0.95241298  0.92175127
 -0.44807362]
[ 0.          0.8559934   6.4053312  -1.61977519 -0.32004039  0.42070095
  1.99520041]


In [16]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
for i in range(len(x)-1):
    print(x[i]-x[i+1])

2
-3
-3
-3
4
-6
-2
9


In [25]:
text = np.loadtxt('num.txt')
hist = np.histogram(x)
for i in range(len(hist)):
    print(sum(hist[i])/len(hist))

4.5
30.25


In [117]:
x = np.array([1, 2, 3, 40])

def sd(a):
    ave = np.mean(a)
    add = []
    for i in range(len(a)):
        add.append((a[i]-ave)**2)
    
    total  = np.sum(add)
        
    print(np.sqrt(total))
    
sd(x)

32.93933818400121
